"""
ALLEX Digital Twin 상수 정의
"""

TOTAL_JOINTS = 59
EFFECTIVE_JOINTS = 49

DEFAULT_JOINT_POSITIONS = [0.0] * TOTAL_JOINTS

DEFAULT_CAMERA_EYE = [2.5, 0.0, 1.5]
DEFAULT_CAMERA_TARGET = [0, 0, 1.0]
DEFAULT_CAMERA_PRIM_PATH = "/OmniverseKit_Persp"

ROBOT_PRIM_PATH = "/ALLEX"
