"""
UI 관련 설정 상수들
"""


class UIColors:
    """UI 색상 상수들"""
    BACKGROUND = 0xFF23211F

    # 버튼 색상
    LOAD_BUTTON_BG = 0xFF0D4F1C
    LOAD_BUTTON_BORDER = 0xFF2ECC40
    LOAD_BUTTON_HOVER = 0xFF1A6B2A

    RED_BUTTON_BG = 0xFF0D0D4F
    RED_BUTTON_BORDER = 0xFF2E2ECC
    RED_BUTTON_HOVER = 0xFF1A1A6B

    STATE_BUTTON_BG = 0xFF0D4F1C
    STATE_BUTTON_BORDER = 0xFF2ECC40
    STATE_BUTTON_HOVER = 0xFF1A6B2A

    YELLOW_BUTTON_BG = 0xFF007ACC
    YELLOW_BUTTON_BORDER = 0xFF00CCFF
    YELLOW_BUTTON_HOVER = 0xFF0099E6

    BLUE_BUTTON_BG = 0xFF7E231E
    BLUE_BUTTON_BORDER = 0xFFD27619
    BLUE_BUTTON_HOVER = 0xFFC06515

    # 사이드바
    SIDEBAR_SUCCESS = 0xFF2ECC40
    SIDEBAR_RESET = 0xFF2E2ECC
    SIDEBAR_STATE = 0xFF2ECC40

    TEXT_PRIMARY = 0xFFFFFFFF


class UILayout:
    """UI 레이아웃 상수들"""
    BUTTON_HEIGHT = 30
    BUTTON_HEIGHT_SMALL = 25
    BUTTON_HEIGHT_LARGE = 35
    LABEL_HEIGHT = 25
    SEPARATOR_HEIGHT = 5

    SPACING_SMALL = 5
    SPACING_MEDIUM = 8

    SIDEBAR_WIDTH = 4
    LABEL_WIDTH_LARGE = 150
    LABEL_WIDTH_XLARGE = 200

    BUTTON_BORDER_WIDTH = 1
    BUTTON_BORDER_RADIUS = 2
    BUTTON_BORDER_RADIUS_LARGE = 3
    BUTTON_MARGIN = 0
    BUTTON_PADDING = 5


class UIConfig:
    """UI 전반적인 설정"""
    WORLD_CONTROLS_COLLAPSED = True
    JOINT_CONTROL_COLLAPSED = True

    PHYSICS_DT = 1 / 50.0
    RENDERING_DT = 1 / 50.0
    GRAVITY = [0, 0, 0.0]
